version: '3'
services:
  postgresql_database:
    container_name: postgresql_container
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=to_do_list
    ports:
      - 3002:5432
  adminer:
    container_name: adminer_container
    image: adminer:4
    ports:
      - 3003:8080
